In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import scipy

In [3]:
from local_pca_utils import make_nearest_neighbors_graph, make_tangents, make_connection, make_general_order_laplacian

from curvature_utils import make_tangents_and_normals, get_second_fundamental_form

In [4]:
from sample_3d_view import sample_sphere, sample_torus, visualize_grid_sphere, visualize_grid_torus

In [5]:
npoints = 1000

In [6]:
2**3

8

In [7]:
ind_a, ind_b = np.triu_indices(2)

In [8]:
ind_a, ind_b

(array([0, 0, 1]), array([0, 1, 1]))

In [9]:
data_s2 = sample_sphere(npoints)

In [10]:
s2_graph = make_nearest_neighbors_graph(data_s2, 7, n=npoints)

100%|██████████| 1000/1000 [00:00<00:00, 18228.02it/s]


In [11]:
tangents = make_tangents(data_s2, s2_graph, 2)

100%|██████████| 1000/1000 [00:00<00:00, 14237.57it/s]


In [12]:
connection = make_connection(tangents, s2_graph)

100%|██████████| 1000/1000 [00:00<00:00, 6658.49it/s]


In [13]:
s2_graph

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 8166 stored elements in List of Lists format>

In [14]:
s_3rd_order_laplacian = make_general_order_laplacian(connection, s2_graph,3, sym=False, zero_trace=False)

100%|██████████| 1000/1000 [00:00<00:00, 1337.34it/s]


In [17]:
eigvals, eigvecs = scipy.sparse.linalg.eigsh(s_3rd_order_laplacian, k=100, which='SM')

In [18]:
eigvals

array([0.0265309 , 0.02653098, 0.02653132, 0.02653136, 0.02653192,
       0.02653257, 0.02830823, 0.02830881, 0.02830976, 0.02831024,
       0.02831147, 0.02831289, 0.02967744, 0.0296788 , 0.0296796 ,
       0.02967968, 0.02968016, 0.02968088, 0.07283325, 0.07283363,
       0.0743812 , 0.07438163, 0.07849532, 0.07849773, 0.08021204,
       0.08021469, 0.08629543, 0.08629563, 0.09018088, 0.09018125,
       0.09394271, 0.09394285, 0.12153068, 0.12153102, 0.1215313 ,
       0.12153139, 0.12153167, 0.12153174, 0.12696056, 0.12696283,
       0.12696344, 0.12696347, 0.12696373, 0.12696546, 0.13764875,
       0.13764922, 0.13764925, 0.13764937, 0.1376498 , 0.13765065,
       0.14579083, 0.14579104, 0.14579132, 0.14579195, 0.1457922 ,
       0.14579318, 0.15344913, 0.15344925, 0.15344964, 0.15344979,
       0.15345024, 0.15345058, 0.24188296, 0.2418831 , 0.24188381,
       0.24188444, 0.24188451, 0.24188453, 0.24350706, 0.24350804,
       0.24904117, 0.24904217, 0.25861368, 0.2586146 , 0.26838

In [ ]:
connection

In [ ]:
connection[(1,1)]

In [ ]:
list(connection.values())[0].shape[0]

In [ ]:
list(connection.values())[0]

In [ ]:
s2_graph.nnz

In [9]:
A = np.arange(0,9).reshape(3,3)

In [10]:
#A = A.T @ A

In [11]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.kron(np.kron(A, A),A)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   2,   0,   2,   4,   0,   0,   0,   0,   2,   4,   0,   4,
          8],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          4,   5,   6,   8,  10,   0,   0,   0,   6,   8,  10,  12,  16,
         20],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          7,   8,  12,  14,  16,   0,   0,   0,  12,  14,  16,  24,  28,
         32],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,   6,   0,
          4,   8,   0,   5,  10,   0,   6,  12,   0,   8,  16,   0,  10,
         20],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   9,  12,  15,  12,
         16,  20,  15,  20,  25,  18,  24,  30,  24,  32,  40,  30,  40,
         50],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  18,  21,  24,  24,
         28,  32,  30,  35,  40,  36,  42,  48,  48,  56,  64,  60,  70,
         80],
       [  0,   0,   0,   0,   0,   0,   

In [13]:
AoA = np.einsum('ik,jl', A, A)

In [ ]:
AoA = AoA.reshape(9,9)

In [ ]:
A3 = np.einsum('ik,jl', AoA, A)

In [ ]:
A3.reshape(27,27)